### PR TITLE
Better version constraint

### PR DESCRIPTION
**Pull request by tractorcow**
Fixes https://github.com/silverstripe/silverstripe-mathspamprotection/issues/45#issuecomment-178879834

### CODE REVIEW

**Comment by tractorcow** [comment]
And no travis, of course. =/

**Comment by tractorcow** [comment]
Ok, added travis and restarted.

**Comment by tractorcow** [comment]
Of course, someone would add a .travis.yml to a module without tests.

**Comment by tractorcow** [comment]
Well, there are no tests to run, but travis at leasts proves that the version constraint isn't broken, so it at least serves a purpose.

**Comment by dhensby** [comment]
that damn robot!

**Comment by dhensby** [comment]
well, we don't have a green tick - maybe we should make the build just be composer install??

**Pull request merged**
